name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: Fath-elpap
          UTC_OFFSET: 3
          THEME: tokyonight
          AUTO_PUSH: false

      - name: Commit and Push Generated Cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile-summary-card-output/

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update GitHub profile summary cards"
            git push
          fi
